# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smBI3GM9U8L-4OP1hQf747ae2-k__zG2
"""

import heapq
import math
import folium
from folium import PolyLine, Marker, Popup, Icon
from folium.plugins import MeasureControl, Fullscreen
from folium.features import DivIcon
import webbrowser
import os

# ============================================================================
# DATA NODE
# ============================================================================
nodes = {
    "N1": {"nama": "Pintu Utama Unesa Ketintang", "lat": -7.311546, "lon": 112.729341, "jenis": "Titik Awal"},
    "N2": {"nama": "Warung Bebek Setia Kawan", "lat": -7.309951, "lon": 112.729843, "jenis": "UMKM"},
    "N3": {"nama": "Nasi Goreng Sedap Malam", "lat": -7.309608, "lon": 112.728266, "jenis": "UMKM"},
    "N4": {"nama": "Simpang Tiga 138", "lat": -7.308197, "lon": 112.725540, "jenis": "Simpang"},
    "N5": {"nama": "Nasi Goreng DUA KARET", "lat": -7.313660, "lon": 112.723320, "jenis": "UMKM"},
    "N6": {"nama": "Simpang Empat Ketintang", "lat": -7.316599, "lon": 112.722444, "jenis": "Simpang"},
    "N7": {"nama": "Bubur Ayam Bandung Teh Eva", "lat": -7.319068, "lon": 112.721995, "jenis": "UMKM"},
    "N8": {"nama": "Sate Cak Faisal", "lat": -7.320807, "lon": 112.721831, "jenis": "UMKM"},
    "N9": {"nama": "Simpang dekat FH", "lat": -7.314317, "lon": 112.728037, "jenis": "Simpang"},
    "N10": {"nama": "Simpang Dekat Danau", "lat": -7.313920, "lon": 112.726679, "jenis": "Simpang"},
    "N11": {"nama": "Simpang Dekat FC baru", "lat": -7.315715, "lon": 112.726007, "jenis": "Simpang"},
    "N12": {"nama": "Simpang Gerbang Belakang UNESA", "lat": -7.317569, "lon": 112.725209, "jenis": "Simpang"},
    "N13": {"nama": "Kedai Larise", "lat": -7.309754, "lon": 112.725173, "jenis": "UMKM"},
    "N14": {"nama": "Persimpangan", "lat": -7.312036, "lon": 112.725447, "jenis": "Simpang"},
    "N15": {"nama": "Simpang Tiga dalam Komplek", "lat": -7.311677, "lon": 112.724677, "jenis": "Simpang"},
    "N16": {"nama": "Persimpangan 2", "lat": -7.312946, "lon": 112.724229, "jenis": "Simpang"},
    "N17": {"nama": "Pesimpangan jalan besar", "lat": -7.312794, "lon": 112.723734, "jenis": "Simpang"},
    "N18": {"nama": "Persimpangan 3", "lat": -7.313221, "lon": 112.725101, "jenis": "Simpang"},
    "N19": {"nama": "Persimpangan 4", "lat": -7.316820, "lon": 112.723790, "jenis": "Simpang"},
    "N20": {"nama": "Persimpangan Kampus", "lat": -7.312819, "lon": 112.728572, "jenis": "Simpang"},
    "N21": {"nama": "Persimpangan Kampus 2", "lat": -7.311935, "lon": 112.726266, "jenis": "Simpang"},
    "N22": {"nama": "Persimpangan Kampus 3", "lat": -7.313549, "lon": 112.725676, "jenis": "Simpang"},
}

# ============================================================================
# DATA EDGE
# ============================================================================
edges_km = [
    ("N1", "N2", 0.18), ("N2", "N3", 0.19), ("N3", "N4", 0.35),
    ("N5", "N6", 0.35), ("N6", "N7", 0.27), ("N20", "N9", 0.18),
    ("N7", "N8", 0.24), ("N1", "N20", 0.19), ("N9", "N10", 0.15),
    ("N10", "N11", 0.21), ("N11", "N12", 0.23), ("N9", "N11", 0.40),
    ("N4", "N13", 0.21), ("N13", "N14", 0.35),
    ("N14", "N15", 0.10), ("N15", "N16", 0.15), ("N16", "N18", 0.097),
    ("N18", "N19", 0.45), ("N16", "N17", 0.057), ("N13", "N17", 0.40),
    ("N17", "N5", 0.11), ("N6", "N19", 0.15), ("N19", "N12", 0.20),
    ("N22", "N10", 0.12), ("N21", "N22", 0.19), ("N20", "N21", 0.27)
]

# ============================================================================
# PARAMETER KECEPATAN
# ============================================================================
KECEPATAN = 20
MENIT_PER_KM = 60 / KECEPATAN

# ============================================================================
# BANGUN GRAF UNTUK A*
# ============================================================================
graph = {node: [] for node in nodes}
jarak_dict = {}
for u, v, jarak in edges_km:
    waktu = jarak * MENIT_PER_KM
    graph[u].append((v, waktu))
    graph[v].append((u, waktu))
    jarak_dict[(u, v)] = jarak
    jarak_dict[(v, u)] = jarak

# ============================================================================
# HEURISTIK EUCLIDEAN
# ============================================================================
def jarak_euclidean_km(lat1, lon1, lat2, lon2):
    dx = (lon2 - lon1) * 111
    dy = (lat2 - lat1) * 111
    return math.sqrt(dx*dx + dy*dy)

def heuristic(node, goal):
    lat1, lon1 = nodes[node]["lat"], nodes[node]["lon"]
    lat2, lon2 = nodes[goal]["lat"], nodes[goal]["lon"]
    return jarak_euclidean_km(lat1, lon1, lat2, lon2) * MENIT_PER_KM

# ============================================================================
# ALGORITMA A*
# ============================================================================
def a_star(start, goal):
    open_set = [(0, start)]
    came_from = {}
    g_score = {node: float('inf') for node in graph}
    g_score[start] = 0
    f_score = {node: float('inf') for node in graph}
    f_score[start] = heuristic(start, goal)

    while open_set:
        _, current = heapq.heappop(open_set)
        if current == goal:
            path = []
            total_jarak = 0.0
            while current in came_from:
                prev = came_from[current]
                path.append(current)
                total_jarak += jarak_dict.get((prev, current), 0)
                current = prev
            path.append(start)
            path.reverse()
            return path, g_score[goal], total_jarak
        for neighbor, weight in graph[current]:
            tentative = g_score[current] + weight
            if tentative < g_score[neighbor]:
                came_from[neighbor] = current
                g_score[neighbor] = tentative
                f_score[neighbor] = tentative + heuristic(neighbor, goal)
                heapq.heappush(open_set, (f_score[neighbor], neighbor))
    return None, float('inf'), 0.0

# ============================================================================
# TENTUKAN START DAN GOAL
# ============================================================================
start_id = "N20"
goal_id = "N8"

path, total_time, total_jarak = a_star(start_id, goal_id)

print("="*60)
print("RUTE TERCEPAT A* - PETA INTERAKTIF DENGAN LABEL JARAK")
print("="*60)
print(f"Start: {nodes[start_id]['nama']} ({start_id})")
print(f"Goal : {nodes[goal_id]['nama']} ({goal_id})")
print(f"Total jarak: {total_jarak:.2f} km")
print(f"Total waktu: {total_time:.2f} menit ({total_time/60:.2f} jam)")

# ============================================================================
# BUAT PETA
# ============================================================================

all_lats = [nodes[n]["lat"] for n in nodes]
all_lons = [nodes[n]["lon"] for n in nodes]
center_lat = sum(all_lats) / len(all_lats)
center_lon = sum(all_lons) / len(all_lons)

m = folium.Map(location=[center_lat, center_lon], zoom_start=15, control_scale=True)
m.add_child(MeasureControl())
m.add_child(Fullscreen())


warna_node = {
    "Titik Awal": "green",
    "UMKM": "orange",
    "Simpang": "blue"
}

for u, v, jarak in edges_km:
    points = [[nodes[u]["lat"], nodes[u]["lon"]], [nodes[v]["lat"], nodes[v]["lon"]]]
    tooltip = f"{nodes[u]['nama']} → {nodes[v]['nama']}<br>Jarak: {jarak:.2f} km<br>Waktu: {jarak*MENIT_PER_KM:.1f} menit"
    PolyLine(points, color="gray", weight=2, opacity=0.6, popup=tooltip).add_to(m)


    mid_lat = (nodes[u]["lat"] + nodes[v]["lat"]) / 2
    mid_lon = (nodes[u]["lon"] + nodes[v]["lon"]) / 2

    folium.Marker(
        location=[mid_lat, mid_lon],
        icon=DivIcon(
            icon_size=(50, 20),
            icon_anchor=(25, 10),
            html=f'<div style="font-size: 10px; font-weight: bold; background-color: white; padding: 2px 4px; border-radius: 8px; border: 1px solid gray; box-shadow: 0 0 2px rgba(0,0,0,0.3);">{jarak:.2f} km</div>',
        )
    ).add_to(m)

if path:
    path_coords = [[nodes[n]["lat"], nodes[n]["lon"]] for n in path]
    folium.PolyLine(
        path_coords,
        color="red",
        weight=6,
        opacity=0.9,
        popup=f"Rute Tercepat<br>Total jarak: {total_jarak:.2f} km<br>Total waktu: {total_time:.2f} menit"
    ).add_to(m)

    for i in range(len(path)-1):
        u, v = path[i], path[i+1]
        jarak_seg = jarak_dict.get((u, v), 0)
        mid_lat = (nodes[u]["lat"] + nodes[v]["lat"]) / 2
        mid_lon = (nodes[u]["lon"] + nodes[v]["lon"]) / 2
        folium.Marker(
            location=[mid_lat, mid_lon],
            icon=DivIcon(
                icon_size=(50, 20),
                icon_anchor=(25, 10),
                html=f'<div style="font-size: 11px; font-weight: bold; background-color: #ffcccc; padding: 2px 5px; border-radius: 10px; border: 1px solid red;">{jarak_seg:.2f} km</div>',
            )
        ).add_to(m)

    for i, nid in enumerate(path):
        info = nodes[nid]
        popup_text = f"<b>{info['nama']}</b><br>Node ID: {nid}<br>Jenis: {info['jenis']}<br>Koordinat: {info['lat']:.6f}, {info['lon']:.6f}"
        if i < len(path)-1:
            next_nid = path[i+1]
            jarak_seg = jarak_dict.get((nid, next_nid), 0)
            waktu_seg = jarak_seg * MENIT_PER_KM
            popup_text += f"<br>→ ke {next_nid}: {jarak_seg:.2f} km ({waktu_seg:.1f} menit)"
        Marker(
            location=[info["lat"], info["lon"]],
            popup=Popup(popup_text, max_width=300),
            icon=Icon(color=warna_node.get(info["jenis"], "gray"), icon="info-sign")
        ).add_to(m)

for nid, info in nodes.items():
    if path and nid in path:
        continue
    popup_text = f"<b>{info['nama']}</b><br>Node ID: {nid}<br>Jenis: {info['jenis']}<br>Koordinat: {info['lat']:.6f}, {info['lon']:.6f}"
    Marker(
        location=[info["lat"], info["lon"]],
        popup=Popup(popup_text, max_width=300),
        icon=Icon(color=warna_node.get(info["jenis"], "gray"), icon="info-sign")
    ).add_to(m)

output_file = "peta_rute_tercepat_ketintang.html"
m.save(output_file)
print(f"\n✅ Peta interaktif dengan label jarak pada setiap edge telah disimpan ke: {output_file}")

try:
    webbrowser.open("file://" + os.path.abspath(output_file))
except:
    pass

try:
    from IPython.display import IFrame, display
    display(IFrame(output_file, width='100%', height=600))
except ImportError:
    pass